[build]
  publish = "public"
  command = "hugo --gc --minify && cp robots.production.txt public/robots.txt"
  functions = "netlify/functions"

[context.production.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.119.0"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.build]
  command = "hugo --gc -b $DEPLOY_PRIME_URL && cp robots.staging.txt public/robots.txt && cp _headers.staging public/_headers"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.119.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"